Fix  lead time and prep time in dine in fulfillment
dailykit/HERN pull request #997
Opened 2022-05-27 08:00 UTC by jayant13o6

## Description
Resolve issues: #987 and #984 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Changes and Fixes
- SCHEDULED_DINEIN replaced with PREODER_DINEIN
- dineInLeadTime and dineInPrepTime columns added in timeSlot table
- New field added in UI form for Slot Interval 

## Screenshots 
(prefer all screen sizes images)
![image](https://user-images.githubusercontent.com/89663357/170656909-3bac7e0b-4c91-446f-8f96-efa3e3b1f0b2.png)

## Checklist
- [x] Database schema is updated
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

Affected Apps
- [ ] Admin
    - [x] Menu>>Recurrences
- [ ] Server
    - [ ] Payment
    - [ ] Email
    - [ ] SMS
    - [ ] Notifications
    - [ ] Integration
    - [ ] Hasura auth
- [ ] Template Engine

2022-05-27 08:20 UTC, ng11tk commented on admin/src/apps/carts/views/forms/ondemand/tunnels/Fulfillment/index.jsx
> +               orderTab.orderFulfillmentTypeLabel === 'PREORDER_DINEIN'
line no. 83 is same as this line

2022-05-27 08:22 UTC, ng11tk requested changes
see the comment for changes

2022-05-27 09:29 UTC, ng11tk approved these changes

2022-05-30 03:11 UTC, rahul72925 commented on admin/src/apps/menu/views/Forms/Recurrences/Main/tunnels/TimeSlotTunnel/index.jsx
> +      value: '00:15',
slot interval format is HH:mm:ss.

2022-05-30 04:03 UTC, jayant13o6 commented on admin/src/apps/menu/views/Forms/Recurrences/Main/tunnels/TimeSlotTunnel/index.jsx
> +      value: '00:15',
yes, it is 15 mins not 15 secs

2022-05-30 07:51 UTC, merged